"""Curated legal-concept → provision map used to seed concept nodes in the knowledge graph.

Bridges the vocabulary gap between how people phrase questions ("anticipatory bail", "cheque bounce", "dowry death")
and statutory language, which often never uses the colloquial term (e.g. CrPC s.438 / BNSS s.482 never say
"anticipatory"). Also encodes the IPC→BNS / CrPC→BNSS / Evidence→BSA transition table for the 2023 codes.
Keys are lower-case phrases; values are (act, section) pairs. Hand-curated from bare-act texts and the
Ministry of Home Affairs comparative tables for the 2023 criminal codes.
"""
IPC = "Indian Penal Code, 1860"; BNS = "Bharatiya Nyaya Sanhita, 2023"
CRPC = "Code of Criminal Procedure Act, 1973"; BNSS = "Bharatiya Nagarik Suraksha Sanhita, 2023"
IEA = "Indian Evidence Act, 1872"; BSA = "Bharatiya Sakshya Adhiniyam, 2023"
COI = "Constitution of India, 1949"; ICA = "Indian Contract Act, 1872"; NIA = "Negotiable Instruments Act, 1881"
MVA = "Motor Vehicles Act, 1988"; HMA = "Hindu Marriage Act, 1955"; DVA = "Protection of Women from Domestic Violence Act, 2005"
CPC = "Code of Civil Procedure, 1908"; SRA = "Specific Relief Act, 1963"; LIM = "Limitation Act, 1963"
ITA = "Information Technology Act, 2000"; RTI = "Right to Information Act, 2005"; CPA = "Consumer Protection Act, 2019"

CONCEPTS: dict[str, list[tuple[str, str]]] = {
    # --- offences against the person
    "murder": [(IPC, "300"), (IPC, "302"), (BNS, "101"), (BNS, "103")],
    "punishment for murder": [(IPC, "302"), (BNS, "103")],
    "culpable homicide": [(IPC, "299"), (IPC, "304"), (BNS, "100"), (BNS, "105")],
    "culpable homicide not amounting to murder": [(IPC, "304"), (BNS, "105")],
    "death by negligence": [(IPC, "304A"), (BNS, "106")],
    "rash and negligent driving": [(IPC, "279"), (IPC, "304A"), (BNS, "281"), (BNS, "106")],
    "attempt to murder": [(IPC, "307"), (BNS, "109")],
    "attempt to commit suicide": [(IPC, "309"), (BNSS, "226")],
    "abetment of suicide": [(IPC, "306"), (BNS, "108")],
    "dowry death": [(IPC, "304B"), (BNS, "80"), (IEA, "113B"), (BSA, "118")],
    "cruelty by husband": [(IPC, "498A"), (BNS, "85")],
    "cruelty to a married woman": [(IPC, "498A"), (BNS, "85")],
    "498a": [(IPC, "498A"), (BNS, "85")],
    "hurt": [(IPC, "319"), (IPC, "323"), (BNS, "114"), (BNS, "115")],
    "grievous hurt": [(IPC, "320"), (IPC, "325"), (BNS, "116"), (BNS, "117")],
    "acid attack": [(IPC, "326A"), (BNS, "124")],
    "wrongful restraint": [(IPC, "339"), (IPC, "341"), (BNS, "126")],
    "wrongful confinement": [(IPC, "340"), (IPC, "342"), (BNS, "127")],
    "assault": [(IPC, "351"), (IPC, "352"), (BNS, "130"), (BNS, "131")],
    "outraging the modesty of a woman": [(IPC, "354"), (BNS, "74")],
    "sexual harassment": [(IPC, "354A"), (BNS, "75")],
    "stalking": [(IPC, "354D"), (BNS, "78")],
    "voyeurism": [(IPC, "354C"), (BNS, "77")],
    "kidnapping": [(IPC, "359"), (IPC, "363"), (BNS, "137")],
    "abduction": [(IPC, "362"), (BNS, "138")],
    "rape": [(IPC, "375"), (IPC, "376"), (BNS, "63"), (BNS, "64")],
    "gang rape": [(IPC, "376D"), (BNS, "70")],
    "unnatural offences": [(IPC, "377")],
    "mob lynching": [(BNS, "103")],
    "organised crime": [(BNS, "111")],
    "terrorist act": [(BNS, "113")],
    "snatching": [(BNS, "304")],
    # --- property offences
    "theft": [(IPC, "378"), (IPC, "379"), (BNS, "303")],
    "extortion": [(IPC, "383"), (IPC, "384"), (BNS, "308")],
    "robbery": [(IPC, "390"), (IPC, "392"), (BNS, "309")],
    "dacoity": [(IPC, "391"), (IPC, "395"), (BNS, "310")],
    "criminal misappropriation": [(IPC, "403"), (BNS, "314")],
    "criminal breach of trust": [(IPC, "405"), (IPC, "406"), (BNS, "316")],
    "receiving stolen property": [(IPC, "411"), (BNS, "317")],
    "cheating": [(IPC, "415"), (IPC, "417"), (IPC, "420"), (BNS, "318")],
    "cheating and dishonestly inducing delivery of property": [(IPC, "420"), (BNS, "318")],
    "mischief": [(IPC, "425"), (IPC, "426"), (BNS, "324")],
    "criminal trespass": [(IPC, "441"), (IPC, "447"), (BNS, "329")],
    "house trespass": [(IPC, "442"), (IPC, "448"), (BNS, "329")],
    "forgery": [(IPC, "463"), (IPC, "465"), (BNS, "336")],
    "counterfeiting currency": [(IPC, "489A"), (BNS, "178")],
    # --- public order / state
    "unlawful assembly": [(IPC, "141"), (BNS, "189")],
    "rioting": [(IPC, "146"), (IPC, "147"), (BNS, "191")],
    "affray": [(IPC, "159"), (BNS, "194")],
    "sedition": [(IPC, "124A"), (BNS, "152")],
    "waging war against the government": [(IPC, "121"), (BNS, "147")],
    "promoting enmity between groups": [(IPC, "153A"), (BNS, "196")],
    "public nuisance": [(IPC, "268"), (BNS, "270")],
    "adulteration of food": [(IPC, "272"), (BNS, "274")],
    "criminal conspiracy": [(IPC, "120A"), (IPC, "120B"), (BNS, "61")],
    "abetment": [(IPC, "107"), (IPC, "109"), (BNS, "45"), (BNS, "49")],
    "common intention": [(IPC, "34"), (BNS, "3")],
    "common object": [(IPC, "149"), (BNS, "190")],
    "right of private defence": [(IPC, "96"), (IPC, "97"), (IPC, "100"), (BNS, "34"), (BNS, "35"), (BNS, "38")],
    "private defence": [(IPC, "96"), (IPC, "100"), (BNS, "34"), (BNS, "38")],
    "insanity defence": [(IPC, "84"), (BNS, "22")],
    "unsoundness of mind": [(IPC, "84"), (BNS, "22")],
    "intoxication": [(IPC, "85"), (IPC, "86"), (BNS, "23"), (BNS, "24")],
    "act of a child": [(IPC, "82"), (IPC, "83"), (BNS, "20"), (BNS, "21")],
    "defamation": [(IPC, "499"), (IPC, "500"), (BNS, "356")],
    "criminal intimidation": [(IPC, "503"), (IPC, "506"), (BNS, "351")],
    "insulting the modesty of a woman": [(IPC, "509"), (BNS, "79")],
    "bigamy": [(IPC, "494"), (BNS, "82")],
    "adultery": [(IPC, "497")],
    "giving false evidence": [(IPC, "191"), (IPC, "193"), (BNS, "227"), (BNS, "229")],
    "perjury": [(IPC, "191"), (IPC, "193"), (BNS, "227"), (BNS, "229")],
    "public servant taking bribe": [(IPC, "161")],
    "punishment of imprisonment for life": [(IPC, "53"), (BNS, "4")],
    "community service": [(BNS, "4"), (BNS, "23")],
    "solitary confinement": [(IPC, "73"), (BNS, "11")],
    # --- procedure
    "anticipatory bail": [(CRPC, "438"), (BNSS, "482")],
    "bail in non-bailable offence": [(CRPC, "437"), (BNSS, "480")],
    "regular bail": [(CRPC, "437"), (CRPC, "439"), (BNSS, "480"), (BNSS, "483")],
    "default bail": [(CRPC, "167"), (BNSS, "187")],
    "bail": [(CRPC, "436"), (CRPC, "437"), (CRPC, "439"), (BNSS, "478"), (BNSS, "480"), (BNSS, "483")],
    "first information report": [(CRPC, "154"), (BNSS, "173")],
    "fir": [(CRPC, "154"), (BNSS, "173")],
    "zero fir": [(BNSS, "173")],
    "arrest without warrant": [(CRPC, "41"), (BNSS, "35")],
    "rights of arrested person": [(CRPC, "50"), (CRPC, "57"), (BNSS, "47"), (BNSS, "58"), (COI, "22")],
    "production before magistrate within 24 hours": [(CRPC, "57"), (BNSS, "58"), (COI, "22")],
    "police custody": [(CRPC, "167"), (BNSS, "187")],
    "remand": [(CRPC, "167"), (BNSS, "187")],
    "charge sheet": [(CRPC, "173"), (BNSS, "193")],
    "police report": [(CRPC, "173"), (BNSS, "193")],
    "cognizable offence": [(CRPC, "2"), (CRPC, "154"), (BNSS, "2"), (BNSS, "173")],
    "non-cognizable offence": [(CRPC, "155"), (BNSS, "174")],
    "summons": [(CRPC, "61"), (BNSS, "63")],
    "warrant of arrest": [(CRPC, "70"), (BNSS, "72")],
    "proclaimed offender": [(CRPC, "82"), (BNSS, "84")],
    "search warrant": [(CRPC, "93"), (BNSS, "96")],
    "maintenance of wife": [(CRPC, "125"), (BNSS, "144")],
    "maintenance": [(CRPC, "125"), (BNSS, "144"), (HMA, "24"), (HMA, "25")],
    "plea bargaining": [(CRPC, "265A"), (BNSS, "289")],
    "compounding of offences": [(CRPC, "320"), (BNSS, "359")],
    "quashing of fir": [(CRPC, "482"), (BNSS, "528")],
    "inherent powers of high court": [(CRPC, "482"), (BNSS, "528")],
    "discharge of accused": [(CRPC, "227"), (CRPC, "239"), (BNSS, "250"), (BNSS, "262")],
    "framing of charge": [(CRPC, "228"), (CRPC, "240"), (BNSS, "251"), (BNSS, "263")],
    "statement of accused": [(CRPC, "313"), (BNSS, "351")],
    "confession before magistrate": [(CRPC, "164"), (BNSS, "183")],
    "recording of statements by police": [(CRPC, "161"), (BNSS, "180")],
    "probation": [(CRPC, "360"), (BNSS, "401")],
    "appeal against conviction": [(CRPC, "374"), (BNSS, "415")],
    "revision": [(CRPC, "397"), (CRPC, "401"), (BNSS, "438"), (BNSS, "442")],
    "trial in absentia": [(BNSS, "356")],
    "witness protection": [(BNSS, "398")],
    "electronic summons": [(BNSS, "63"), (BNSS, "64")],
    "limitation for taking cognizance": [(CRPC, "468"), (BNSS, "514")],
    # --- evidence
    "dying declaration": [(IEA, "32"), (BSA, "26")],
    "confession": [(IEA, "24"), (IEA, "25"), (IEA, "26"), (BSA, "22"), (BSA, "23")],
    "confession to police": [(IEA, "25"), (BSA, "23")],
    "burden of proof": [(IEA, "101"), (IEA, "102"), (BSA, "104"), (BSA, "105")],
    "presumption of innocence": [(IEA, "101"), (BSA, "104")],
    "hostile witness": [(IEA, "154"), (BSA, "157")],
    "electronic evidence": [(IEA, "65B"), (BSA, "63")],
    "electronic record": [(IEA, "65B"), (BSA, "63")],
    "admission": [(IEA, "17"), (IEA, "21"), (BSA, "15"), (BSA, "19")],
    "hearsay": [(IEA, "60"), (BSA, "55")],
    "res gestae": [(IEA, "6"), (BSA, "4")],
    "expert opinion": [(IEA, "45"), (BSA, "39")],
    "estoppel": [(IEA, "115"), (BSA, "121")],
    "privileged communication": [(IEA, "122"), (IEA, "126"), (BSA, "128"), (BSA, "132")],
    "cross-examination": [(IEA, "137"), (IEA, "138"), (BSA, "140"), (BSA, "143")],
    "leading question": [(IEA, "141"), (BSA, "146")],
    "presumption as to dowry death": [(IEA, "113B"), (BSA, "118")],
    # --- constitution
    "right to equality": [(COI, "14"), (COI, "15"), (COI, "16")],
    "equality before law": [(COI, "14")],
    "reservation": [(COI, "15"), (COI, "16"), (COI, "335")],
    "untouchability": [(COI, "17")],
    "freedom of speech": [(COI, "19")],
    "freedom of speech and expression": [(COI, "19")],
    "fundamental rights": [(COI, "12"), (COI, "13"), (COI, "14"), (COI, "19"), (COI, "21"), (COI, "32")],
    "double jeopardy": [(COI, "20")],
    "self-incrimination": [(COI, "20")],
    "right to life": [(COI, "21")],
    "right to life and personal liberty": [(COI, "21")],
    "right to privacy": [(COI, "21")],
    "right to education": [(COI, "21A"), (COI, "45")],
    "preventive detention": [(COI, "22")],
    "right against exploitation": [(COI, "23"), (COI, "24")],
    "child labour": [(COI, "24")],
    "freedom of religion": [(COI, "25"), (COI, "26"), (COI, "28")],
    "minority rights": [(COI, "29"), (COI, "30")],
    "right to constitutional remedies": [(COI, "32")],
    "writ jurisdiction": [(COI, "32"), (COI, "226")],
    "habeas corpus": [(COI, "32"), (COI, "226")],
    "directive principles": [(COI, "36"), (COI, "37"), (COI, "38"), (COI, "39")],
    "uniform civil code": [(COI, "44")],
    "fundamental duties": [(COI, "51A")],
    "president of india": [(COI, "52"), (COI, "53"), (COI, "54"), (COI, "61")],
    "impeachment of president": [(COI, "61")],
    "pardoning power": [(COI, "72"), (COI, "161")],
    "money bill": [(COI, "110")],
    "ordinance": [(COI, "123"), (COI, "213")],
    "supreme court": [(COI, "124"), (COI, "131"), (COI, "132"), (COI, "136"), (COI, "141"), (COI, "142")],
    "special leave petition": [(COI, "136")],
    "judicial review": [(COI, "13"), (COI, "32"), (COI, "226")],
    "high court": [(COI, "214"), (COI, "226"), (COI, "227")],
    "panchayat": [(COI, "243"), (COI, "243A"), (COI, "243B")],
    "municipality": [(COI, "243P"), (COI, "243Q")],
    "emergency": [(COI, "352"), (COI, "356"), (COI, "360")],
    "national emergency": [(COI, "352")],
    "president's rule": [(COI, "356")],
    "financial emergency": [(COI, "360")],
    "amendment of the constitution": [(COI, "368")],
    "basic structure": [(COI, "368")],
    "official language": [(COI, "343")],
    "election commission": [(COI, "324")],
    "comptroller and auditor general": [(COI, "148")],
    "attorney general": [(COI, "76")],
    "governor": [(COI, "153"), (COI, "155"), (COI, "161")],
    # --- civil / commercial
    "cheque bounce": [(NIA, "138"), (NIA, "139"), (NIA, "142")],
    "dishonour of cheque": [(NIA, "138"), (NIA, "142")],
    "promissory note": [(NIA, "4")],
    "bill of exchange": [(NIA, "5")],
    "offer and acceptance": [(ICA, "2"), (ICA, "3"), (ICA, "7")],
    "consideration": [(ICA, "2"), (ICA, "25")],
    "free consent": [(ICA, "13"), (ICA, "14")],
    "coercion": [(ICA, "15")],
    "undue influence": [(ICA, "16")],
    "fraud": [(ICA, "17")],
    "misrepresentation": [(ICA, "18")],
    "void agreement": [(ICA, "24"), (ICA, "25"), (ICA, "26"), (ICA, "27"), (ICA, "28"), (ICA, "29"), (ICA, "30")],
    "agreement in restraint of trade": [(ICA, "27")],
    "wagering agreement": [(ICA, "30")],
    "contingent contract": [(ICA, "31")],
    "quasi contract": [(ICA, "68"), (ICA, "70")],
    "breach of contract": [(ICA, "73"), (ICA, "74")],
    "liquidated damages": [(ICA, "74")],
    "indemnity": [(ICA, "124")],
    "guarantee": [(ICA, "126")],
    "bailment": [(ICA, "148")],
    "pledge": [(ICA, "172")],
    "agency": [(ICA, "182")],
    "specific performance": [(SRA, "10"), (SRA, "14")],
    "injunction": [(SRA, "36"), (SRA, "37"), (SRA, "38"), (CPC, "39")],
    "res judicata": [(CPC, "11")],
    "limitation period": [(LIM, "3"), (LIM, "5")],
    "condonation of delay": [(LIM, "5")],
    "divorce": [(HMA, "13"), (HMA, "13B")],
    "mutual consent divorce": [(HMA, "13B")],
    "restitution of conjugal rights": [(HMA, "9")],
    "judicial separation": [(HMA, "10")],
    "domestic violence": [(DVA, "3"), (DVA, "12"), (DVA, "18")],
    "protection order": [(DVA, "18")],
    "hit and run": [(MVA, "161"), (BNS, "106")],
    "drunken driving": [(MVA, "185")],
    "third party insurance": [(MVA, "146"), (MVA, "147")],
    "hacking": [(ITA, "43"), (ITA, "66")],
    "identity theft": [(ITA, "66C")],
    "cyber stalking": [(ITA, "66E"), (IPC, "354D")],
    "publishing obscene material online": [(ITA, "67")],
    "right to information": [(RTI, "3"), (RTI, "6"), (RTI, "8")],
    "consumer complaint": [(CPA, "35")],
    "deficiency in service": [(CPA, "2"), (CPA, "35")],
}
