import { toast } from "./store";
export function download(name: string, content: string, type = "text/markdown") { const b = new Blob([content], { type }); const a = document.createElement("a"); a.href = URL.createObjectURL(b); a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 2000); toast(`Downloaded ${name}`); }
export async function copy(text: string) { try { await navigator.clipboard.writeText(text); toast("Copied to clipboard"); } catch { toast("Copy failed", "err"); } }
export function printSection(title: string, html: string) {
  const w = window.open("", "_blank", "width=900,height=700"); if (!w) return toast("Pop-up blocked", "warn");
  w.document.write(`<html><head><title>${title}</title><style>body{font:15px/1.6 Inter,system-ui,sans-serif;color:#111;padding:40px;max-width:800px;margin:auto}h1,h2,h3{font-family:Georgia,serif}.cite{font:600 11px monospace;border:1px solid #2a9d8f;border-radius:9px;padding:0 5px;color:#2a9d8f}small{color:#666}</style></head><body><h1>${title}</h1>${html}<hr/><small>Generated by LawLine AI · legal information, not legal advice.</small></body></html>`);
  w.document.close(); w.focus(); setTimeout(() => w.print(), 300);
}
